config/routes.rb
Blog::Application.routes.draw do

  get "pages/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "users/index"

  devise_for :users , path_names: {sign_in: "login" , sign_out: "logout" }

  resources :users
  resources :brands
  resources :categories
  resources :products
  resources :images
  resources :pages

   root :to => 'pages#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  #attr_accessible :description, :name, :logo  
  attr_protected
  has_attached_file :logo,  :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_and_belongs_to_many :categories
  # has_attached_file :logo, 
  # :styles => lambda{ |a| ["image/jpeg", "image/png","image/gif","image/pjpeg", "image/x-png","image/jpg"].include?( a.content_type ) ? { :thumb => "60x60#" } : {}  }
   # before_save do
   #   self.logo = self.logo.resize "60x60"
   # end
  
end

app/models/brand_category.rb
class BrandCategory < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/brands_category.rb
class BrandsCategory < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description,:name, :parent_id
  #attr_protected :lft, :rgt
  
  acts_as_nested_set
  #accepts_nested_attributes_for :brands, allow_destroy: true
  validates :name, :presence => true
  has_and_belongs_to_many :brands
  def self.nested_dropdown
    categories = self.order(:lft).collect {|row| ["#{'-- '*row.depth} #{row.name}",row.id]}
  end
 
end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :product
  has_attached_file :photo,  :styles => {:large=>"900x300#" ,:medium => "200x100", :thumb => "60x60#" }
  attr_protected
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_protected

  validates :name, :presence => true  
  validates :category, :presence => true

  belongs_to :category
  belongs_to :user
  belongs_to :brand
 
  has_many :images
  accepts_nested_attributes_for :images, :allow_destroy=>true
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
   
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:token_authenticatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:admin,:avatar
  # attr_accessible :title, :body

  validates :email , :presence => true, :uniqueness => true
  has_and_belongs_to_many :categories
  has_attached_file :avatar,  :styles => { :medium => "100x100>", :thumb => "60x60#" }

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :mypage
  #before_filter :custom_method, :only => [:new, :edit, :create, :destroy]
  private
	def custom_method
	  authenticate_user!
	  if current_user.admin?
	     return
	  else
	     redirect_to root_url # or whatever
	  end
	end
	def mypage
		 @page_products =  Product.all 
  		 @page_categories = Category.all 	 
  		 @page_brands = Brand.all
  		 @page_brands_categories = BrandsCategory.all
	end
end

app/controllers/brands_controller.rb
class BrandsController < InheritedResources::Base
	#layout "welcome"
	before_filter :authenticate_user!
	before_filter :custom_method, :only => [:new, :edit, :create, :destroy]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	#layout "welcome"
	before_filter :authenticate_user!
	before_filter :custom_method, :only => [:new, :edit, :create, :destroy]
	def index		                            
          @categories = Category.all                                      
	end
	def new
		@category = Category.new
	end
	def create
		@category = Category.new(params[:category])
		if @category.save
			redirect_to categories_path
		else
			render :action=>"new"
		end
	end
	def edit
		@category = Category.find(params[:id])
	end
	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(params[:category])
			redirect_to categories_path
		else
			render :action=>"edit"
		end
	end
	def show
		@category = Category.find(params[:id])		
	end
	def destroy 
		@category = Category.find(params[:id])
    	@category.destroy
		redirect_to categories_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   before_filter :authenticate_user!	
  def index  	
  	if params[:products]
  		render :text=>params.inspect and return false
  	else
  		@pages = Product.all
  	end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :authenticate_user!	
	before_filter :custom_method, :only => [:new, :edit, :create, :destroy]
	def index		                            
          @products = Product.all     
	end
	def new
		@product = Product.new 
	end
	def create
		@product = Product.new(params[:product])
		if @product.save
			redirect_to products_path
		else
			render :action=>"new"
		end
	end
	def edit
		@product = Product.find(params[:id])
	end
	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to products_path
		else
			render :action=>"edit"
		end
	end
	def show
		@product = Product.find(params[:id])		
	end
	def destroy 
		@product = Product.find(params[:id])
    	@product.destroy
		redirect_to products_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
  	@users = User.all  	
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_form.html.erb
<%= form_for @brand, :html => { :class => 'form-horizontal' ,:multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :categories, :class => 'control-label' %>
    <div class="controls">
     <% Category.where(:parent_id=>nil).all.each do |i| %>
      <label class="checkbox inline">
        <%= check_box_tag "brand[category_ids][]", i.id %><%= i.name %>
      </label>
     <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' ,:cols=>25 ,:rows=>5 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :logo %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                brands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/brands/index.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:logo) %></th>    
      <!-- <th><%#= model_class.human_attribute_name(:logo_updated_at) %></th>
      <th><%#= model_class.human_attribute_name(:created_at) %></th> -->
     <% if current_user.admin? %>
      <th><%=t '.actions', :default => t("helpers.actions")  %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to brand.id, brand_path(brand) %></td>
        <td><%= brand.name %></td>
        <td><%= brand.description %></td>
        <td><%= image_tag brand.logo.url(:thumb)%></td>       
        <!-- <td><%#= brand.logo_updated_at %></td>
        <td><%#=l brand.created_at %></td> -->
         <% if current_user.admin? %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_brand_path(brand), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      brand_path(brand),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_brand_path,
            :class => 'btn btn-primary' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:parent_id) %></th>
      <th><%= model_class.human_attribute_name(:lft) %></th>
      <th><%= model_class.human_attribute_name(:rgt) %></th>
      <th><%= model_class.human_attribute_name(:depth) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% if current_user.admin? %>
      <th><%=t '.actions', :default => t("helpers.actions")  %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%= category.parent_id %></td>
        <td><%= category.lft %></td>
        <td><%= category.rgt %></td>
        <td><%= category.depth %></td>
        <td><%= category.description %></td>
        <td><%=l category.created_at %></td>
         <% if current_user.admin? %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' if current_user.admin? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

     <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Blog</a>
          <div class="container nav-collapse">
          	<ul class="nav" style="float:left">
          		 <!--  <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li> -->
          	</ul>
            <ul class="nav" style="float:right">            
			  <% if user_signed_in? %>	
			    <!-- <li><%#=link_to image_tag(current_user.avatar, :height=>50 ,:width=>50),edit_user_registration_path  %></li>	 -->	          
			    <li> <%= link_to current_user.email, edit_user_registration_path %></li>
			    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
			  <% else %>
			    <li><%= link_to "Sign up", new_user_registration_path %> </li>
			    <li><%= link_to "Login", new_user_session_path %></li>
	          <% end %>
            </ul> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>   
    <br /><br />
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="#">&nbsp;&nbsp;</a>
        <ul class="nav .nav-pills">
          <li class="active"><a href="#">Home</a></li>
          <%#= debug @page_products.inspect %>
          <% Category.each_with_level(Category.root.self_and_siblings) do |category, level|  %>     
          <li class="dropdown">
            <%#= link_to category.name ,category_path(category) %>
            <a class="dropdown-toggle"
               data-toggle="dropdown"
               href="/categories/<%=category.id%>">
                <%= category.name %>               
              </a>
            <ul class="dropdown-menu">
              <% category.descendants.each do |sub_cat| %>
                <li class="dropdown-submenu">
                  <%=link_to sub_cat.name %>
                    <ul class="dropdown-menu">
                      <% brand_categories = @page_brands_categories.collect{|x| x.brand_id if x.category_id == category.id }.compact %>                      
                      <% @page_brands.each do |brand| %>
                        <% if brand_categories.include?(brand.id)  %>
                        <li><%=link_to brand.name ,brands_path  %></li>
                        <% end %>
                      <%end%>
                    </ul>
                </li> 
              <% end %>                       
            </ul>   

          </li>
          <% end %>  
          <li class="dropdown">
          </li>      
        </ul>
      </div>
    </div>
    </center>



    <div class="container">
        <div class="row">
          <div class="span9">          	
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, id: "flash_#{name}" %>
              <% end %>
             <%= yield %>
          </div>
          <!-- <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div>
          </div></span--> 
        </div><!--/row-->

      <footer>
        <p>&copy; Feature Ecommerce Blog</p>
      </footer>

    </div> <!-- /container -->
   
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
    <style type="text/css">
    #myheader-inner{
     background: #3032ba; /* Old browsers */
background: -moz-linear-gradient(top, #3032ba 0%, #335ace 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#3032ba), color-stop(100%,#335ace)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top, #3032ba 0%,#335ace 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top, #3032ba 0%,#335ace 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top, #3032ba 0%,#335ace 100%); /* IE10+ */
background: linear-gradient(to bottom, #3032ba 0%,#335ace 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3032ba', endColorstr='#335ace',GradientType=0 ); /* IE6-9 */
    }
    </style>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner" >
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Blog</a>
          <div class="container nav-collapse">
            <ul class="nav" style="float:left">
               <!--  <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li> -->
            </ul>
            <ul class="nav" style="float:right">            
        <% if user_signed_in? %>  
          <!-- <li><%#=link_to image_tag(current_user.avatar, :height=>50 ,:width=>50),edit_user_registration_path  %></li>  -->            
          <li> <%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %> </li>
          <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
            </ul> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <br /><br />
    <div class="navbar">
      <div class="navbar-inner" id="myheader-inner" >
        <a class="brand" href="#">&nbsp;&nbsp;</a>
        <ul class="nav .nav-pills">
          <li class="active" ><a href="#"><b style="color:blue">Home</b></a></li>
          <% Category.where(:parent_id => nil).all.each do |category|  %>     
          <li class="dropdown">
            <%#= link_to category.name ,category_path(category) %>           
                <a class="dropdown-toggle"
               data-toggle="dropdown"
               href="/categories/<%=category.id%>">
                 <%= category.name %>
              </a>
           
            <ul class="dropdown-menu">
              <% Category.find_all_by_parent_id(category.id).each do |sub_cat| %>
                <li class="dropdown-submenu">
                  <%=link_to sub_cat.name , category_path(sub_cat) %>
                    <ul class="dropdown-menu">
                      <% Brand.all.sort.each do |brand| %>
                      <li><%=link_to brand.name ,brand_path(brand.name) %></li>
                      <%end%>
                    </ul>
                </li>
              <%end%>              
            </ul>   

          </li>
          <% end %>  
          <li class="dropdown">
          </li>      
        </ul>
      </div>
    </div>

   
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
         
        </div>
        <div class="span8">
            <div id="myCarousel" class="carousel slide">  
              <!-- Carousel items -->  
              <div class="carousel-inner">  
                <div class="active item"> <%= image_tag "/assets/image9.jpg" ,:height=>100 ,:width=>1000 %></div> 
                 <% for i in 10..16 %>
                  <div class="item">                              
                   <%= image_tag "/assets/image#{i}.jpg" ,:height=>100 ,:width=>1000 %>
                  </div>
                 <% end %>
                </div>  
              <!-- Carousel nav -->  
              <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>  
              <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>  
            </div>

            <ul class="thumbnails">
              <% @products.each do |product| %>
              <li class="span3">
                <div class="thumbnail">
                  <%=image_tag product.images[0].photo ,:height=>200 , :width=>300 if product.images.length > 0 %>
                  <!-- <img src="http://placehold.it/300x200" alt=""> -->
                  <h3><%=product.name %></h3>
                  <h5><%= product.brand.name %></h5>
                  <p><%= truncate(product.description, :length => 100 ) %><h4 style="color:blue;"><%= link_to "More.." ,product_path(product) %></h4></p>
                  <!-- <p><%#= product.category.name %><br><%#= product.description ,:truncate=>20 %></p> -->
                </div>
              </li>
              <% end %>
            </ul>

           <%= yield %>
        </div>
        <div class="span2">
          
        </div>
      </div> 
    </div> 

    <div class="navbar navbar-static-bottom">
      <div class="navbar-inner" >
        <div class="container">
         <!--  <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a> -->
          <!-- <a class="brand" href="#">Popular Brands</a>  -->         
          <div class="container nav-collapse">
            <ul class="nav" style="float:left">
              <% Brand.all.collect do |brand| %>
              <li><%= link_to image_tag(brand.logo.url), brand_path(brand.name) ,:height=>30,:width=>50 %></li>
              <% end %>              
            </ul>        
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <!-- <th><%#= model_class.human_attribute_name(:user_id) %></th> -->
      <th><%= model_class.human_attribute_name(:brand_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:features) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% if current_user.admin? %>
      <th><%=t '.actions', :default => t("helpers.actions")  %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%=image_tag product.images[0].photo(:thumb)  if product.images.length > 0 %></td>
        <td><%= product.category.name %></td>
        <!-- <td><%#= product.user_id %></td> -->
        <td><%= product.brand.name %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.active %></td>
        <td><%= product.features %></td>
        <td><%= product.description %></td>
        <td><%=l product.created_at %></td>
        <% if current_user.admin? %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' if current_user.admin?%>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' if current_user.admin?%>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' if current_user.admin? %>